services:
  agent_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - path: app
          action: sync+restart
          target: app
